### ISSUE TITLE
Add install requirement to README

### ISSUE THREAD

**Issue by jeff-matthews** [magento-devdocs/zendesk-to-jekyll#1]
I had to install `pry` to use this on my machine. You might want to add that to the README.

Here's the error I got:

```
ruby zendesk_jekyllizer.rb how-to.json
Traceback (most recent call last):
	2: from zendesk_jekyllizer.rb:8:in `<main>'
	1: from /Users/jeffmatthews/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/jeffmatthews/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pry (LoadError)
```

And here's how I fixed it:

```
gem install pry
```

**Comment by dshevtsov** [comment]
Thank you for the feedback. I removed the dependency on pry. It was required only for development.
